author: "Codeliter <hackzlord at gmail.com>"
category: "http"
summary: "Push offline messages to a URL"
home: "https://github.com/processone/ejabberd-contrib/tree/master/"
url: "git@github.com:processone/ejabberd-contrib.git"